parser: babel-eslint

extends:
  - eslint:recommended
  - plugin:react/recommended

rules:
  comma-dangle: [error, always-multiline]
  no-constant-condition: 0
  curly: [error, multi-line]
  no-var: error
  quotes: error
  brace-style: [error, stroustrup]
  semi: [error, never]

  filenames/match-exported: error
  react/no-unknown-property: off
  react/prop-types: off
  react/display-name: off

env:
  node: true
  es6: true

plugins:
  - filenames
  - react

settings:
  react:
    pragma: h
